# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "eventra"
client_id = "416fc6e270de506565ca1f79517832ba"
application_url = "https://eventrabusiness-production.up.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [
  "https://eventrabusiness-production.up.railway.app/auth/callback",
  "https://eventrabusiness-production.up.railway.app/auth/shopify/callback",
  "https://eventrabusiness-production.up.railway.app/api/auth"
]

[build]
automatically_update_urls_on_dev = true
